# APP_NAME = dtces

# DOCKER_USERNAME: raizv
# DOCKER_EMAIL: raizvih@gmail.com
# DOCKER_PASSWORD: Qweafsfasdfrty213231231
# DOCKER_REPO: $DOCKER_USERNAME/$APP_NAME
# DOCKER_IMG_TAG: latest

# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
# AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# AWS_DEFAULT_REGION=us-east-1
# AWS_S3_BUCKET=dtces-dev-eb-dockerrun
# AWS_S3_KEY=Dockerrun.aws.json

git:
  depth: 3

branches:
  only:
    - travis

sudo: required

language: ruby

services:
  - docker

env:
  RACK_ENV: dev

before_install:
  - sudo pip install awscli
  - docker --version
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD

script:
  - export TAG=`git tag --contains $TRAVIS_COMMIT`
  - docker build -t $DOCKER_REPO:$TAG .
  - docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker push $DOCKER_REPO

after_success:
  - sed -i "s/latest/$TAG/g" build/Dockerrun.aws.json
  - aws s3 cp build/ s3://$AWS_S3_BUCKET --recursive
  - aws elasticbeanstalk create-application-version --region us-east-1 --application-name dtces --version-label $TAG --description $TRAVIS_COMMIT --source-bundle S3Bucket="dtces-dev-eb-dockerrun",S3Key="Dockerrun.aws.json"
  - aws elasticbeanstalk update-environment --environment-name dtces-dev --version-label $TAG --region us-east-1


#  CURRENT_TAG=`git describe --tags --exact-match $TRAVIS_COMMIT 2> /dev/null`
#  if [ "$TRAVIS_BRANCH" = "$CURRENT_TAG" ]; then
#    # this is a tag build
#    ...
