version: '2'

services:
  db:
    image: cassandra:3.0

  app:
    build: .
#    env_file: .env
    depends_on:
      - db
    ports:
      - 9292:9292

#- rake create [-E env]
#- rake migrate [-E env]
#- rackup [-E env]

# dc run app bundle exec rake create
# dc run app bundle exec rake migrate
